print("#######################################")
print("##### MAD ###### LIPS #################")
print()
clr = input("Your favourite color is : ")
tng = input("Most useful thing is : ")
pet = input("dream pet : ")
print("Roses are " + clr )
print( tng + " is blue")
print( pet + " loves You")
print()
print("#######################################")
print("##### THANK ##### YOU #################")
print("#######################################")
